= Mediatek BSP

Ubuntu Host: 16.04 or 18.04

Install some dependence package 

[source,console]
$: sudo apt-get update && \
    sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib \
    build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
    xz-utils debianutils iputils-ping libsdl1.2-dev xterm tar locales curl


To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir mediatek-bsp
$: cd mediatek-bsp
$: repo init -u https://github.com/nguyenvuhung/yocto-bsp-platform -b zeus_mediatek
$: repo sync -j"$(nproc --all)"

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: MACHINE=mt7623-bpi-r2 DISTRO=poky source setup-environment build
$: bitbake core-image-mtk-swu
or
$: bitbake qt5-image-demo-swu   (Release Offical)

You can use any directory to host your build.

The source code is checked out at `Mediatek-bsp/sources`.

== Contributing

To contribute to this layer you should send the patches for review to the mailing list.

Mailing list::
    https://lists.yoctoproject.org/listinfo/meta-freescale

Source code::
    https://github.com/nguyenvuhung/bbb-community-bsp-platform

When creating patches, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='fsl-community-bsp-platform][PATCH][thud' origin

When sending patches, please use something like:

[source,console]
$: git send-email --to meta-freescale@yoctoproject.org <generated patch>

== Using Development and Testing Branches

Replace the `repo init` command above with one of the following:

master:: For developers
+
[source,console]
$: repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master

master-next:: For intrepid developers and testers
+
Patches are typically merged into master-next and then are merged into master after a testing and comment period. It's possible that master-next has something you want or need. But it's also possible that using master-next breaks something that was working before. Use with caution.

[source,console]
$: repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master-next
